Repository windup/windup_integration_test, pull requests merged in 2020-05, with the labels that each got.

#12 [1LP][RFR]: DropdownMenu widget for Setting and help
  rhamt/entities/__init__.py
  rhamt/widgetastic/__init__.py
Labels: enhancement, framework

#10 RFR: Basic rhamt notebook
  rhamt/notebooks/rhamt_console.ipynb
  setup.cfg
Labels: enhancement

#9 [1LP][RFR]: Fix navigations and introduce all method for projects
  rhamt/entities/__init__.py
  rhamt/entities/projects.py
  rhamt/tests/test_multiple_projects_Test02.py
  rhamt/tests/test_projects_Test01.py
Labels: bug, fix_framework

#11 [1LP][RFR]: ProjectList widget supporting all operations
  rhamt/exceptions.py
  rhamt/widgetastic/__init__.py
Labels: framework

#14 [RFR]Fixed test for multiple apps
  rhamt/entities/__init__.py
  rhamt/entities/analysis_configuration.py
  rhamt/entities/projects.py
  rhamt/tests/test_multiple_projects_Test02.py
  rhamt/tests/test_projects_Test01.py
  rhamt/widgetastic/__init__.py
Labels: fix_test
