Repository windup/windup_integration_test, pull requests merged in 2020-03, with the labels that each got.

#2 RFR: Test framework
  .github/workflows/main.yml
  entry_points.txt
  rhamt/fixtures/__init__.py
  rhamt/fixtures/application.py
  rhamt/test_framework/__init__.py
  rhamt/test_framework/pytest_plugin.py
  rhamt/tests/test_login.py
  rhamt/tests/test_utils.py
Labels: enhancement, framewrok

#3 update readme basic
  README.md
  README.rst
  setup.cfg
Labels: documentation

#4 updating license
  LICENSE
Labels: documentation

#5 Selenium Container
  .gitignore
  README.md
  rhamt/conf/selenium.yaml
  rhamt/scripting/cli.py
  rhamt/scripting/selenium_container.py
Labels: enhancement, framewrok

#6 Fix Log changes
  rhamt/log/rhamt.log
  rhamt/scripting/shell.py
  rhamt/utils/conf.py
  rhamt/utils/log.py
  rhamt/utils/path.py
Labels: fix_framework

#7 typos
  entry_points.txt
  setup.cfg
Labels: bug

#8 [RFR] Create Project test
  entry_points.txt
  rhamt/conf/credentials.yaml
  rhamt/conf/env.yaml
  rhamt/entities/__init__.py
  rhamt/entities/analysis_results.py
  rhamt/entities/projects.py
  rhamt/tests/test_projects.py
  rhamt/utils/ftp.py
  rhamt/widgetastic/__init__.py
Labels: enhancement, framework, new_test
