Repository windup/windup_integration_test, pull requests merged in 2021-04, with the labels that each got.

#79 RFR: Added polarion connector to dump test cases automatically
  .pre-commit-config.yaml
  conf/polarion_requirements.yaml
  conf/polarion_tools.yaml
  mta/tests/.polarion_tests
  mta/tests/test_advanced_options.py
  mta/tests/test_analysis_results.py
  mta/tests/test_applications.py
  mta/tests/test_global_labels.py
  mta/tests/test_global_rules.py
  mta/tests/test_login.py
  mta/tests/test_multiple_projects.py
  mta/tests/test_projects.py
  mta/tests/test_report.py
  mta/tests/test_utils.py
  setup.cfg
Labels: documentation, enhancement

#83 [RFR] Automated default path selection test case
  mta/tests/test_projects.py
  mta/widgetastic/__init__.py
Labels: new-automation

#82 RFR: Added test cases from polarion to automate
  mta/entities/global_config/rules_configuration.py
  mta/entities/report.py
  mta/tests/test_global_rules.py
  mta/tests/test_report.py
  mta/widgetastic/__init__.py
Labels: manual-tests
